name: Build OpenJDK Mobile for ios sim

on:
  workflow_call:

jobs:
  build:
    runs-on: macos-14

    steps:
      - name: 'Install toolchain and dependencies'
        run: |
          brew install libffi
          brew install autoconf make
          sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
          echo '/usr/local/opt/make/libexec/gnubin' >> $GITHUB_PATH

      - name: Checkout builder repo
        uses: actions/checkout@v3

      - name: Set up JDK 25
        uses: actions/setup-java@v4
        with:
          java-version: '25'
          distribution: 'temurin'

      - name: Download and unzip mobile-support
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release download libffi-build --pattern "libffi-ios-sim.zip"
          mkdir -p ../support
          unzip libffi-ios-sim.zip -d ../support

      - name: Clone OpenJDK Mobile sources
        run: |
          git clone https://github.com/kolbyml/mobile.git
          cp openjdk-ext/src/hotspot/symbol_keeper.cpp mobile/src/hotspot/os/bsd
          cd mobile
          git checkout master
          
          bash configure \
          --with-conf-name=iossim-aarch64-zero-release \
          --disable-warnings-as-errors \
          --openjdk-target=aarch64-macos-ios \
          --with-sysroot=/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk \
          --with-libffi-include=$(realpath ../../support/include/ffi) \
          --with-libffi-lib=$(realpath ../../support) \
          --with-extra-cflags="-target arm64-apple-ios-simulator -mios-simulator-version-min=18.2" \
          --with-extra-cxxflags="-target arm64-apple-ios-simulator -mios-simulator-version-min=18.2" \
          --with-cups-include=$(xcrun --sdk macosx --show-sdk-path)/usr/include
          
          # Explicitly build the modules required for the JRE bundle
          make LOG=cmdlines,info CONF=iossim-aarch64-zero-release static-libs-image \
          MODULES="java.base java.compiler java.datatransfer java.desktop java.instrument java.logging java.management java.naming java.prefs java.scripting java.se java.security.jgss java.security.sasl java.sql java.transaction.xa java.xml jdk.attach jdk.crypto.ec jdk.jdi jdk.management jdk.net jdk.unsupported jdk.unsupported.desktop jdk.zipfs jdk.accessibility jdk.charsets jdk.localedata"

      - name: Upload device artifact
        uses: actions/upload-artifact@v4
        with:
          name: libjvm-simulator
          path: |
            mobile/build/iossim-aarch64-zero-release/images/static-libs/lib
            mobile/build/iossim-aarch64-zero-release/jdk/conf
            mobile/build/iossim-aarch64-zero-release/jdk/include

      - name: Upload java
        uses: actions/upload-artifact@v4
        with:
          name: java.simulator
          path: |
            mobile/build/iossim-aarch64-zero-release/jdk/modules